version: "3"

services:
  micro1-api:
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - ./micro1-api:/micro1-api
    command: >
      sh -c "python manage.py wait_for_db &&
             pip install -r /requirements.txt
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8888"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password